### ISSUE TITLE
check script does not work with python2.7

### ISSUE THREAD

**Issue by 3dfxatwork** [freifunk/icvpn-scripts#33]
The check script does not work with python 2.7, with python 3 it works perfect. Can you add a hint to use python3 or add compatibility for 2.7 ?

**Comment by mweinelt** [comment]
There is a note at https://github.com/freifunk/icvpn-scripts#debian-wheezy-oldstable,

**Comment by 3dfxatwork** [comment]
Yes but:
* i'm not using oldstable (it's jessie 8.1), so normaly i can ignore hint in this section
* it's not complaining about a missing lib, it's complaining about a syntax error: 

   File "../icvpn-scripts/check", line 22
    print(ANSI_COLOR_ERR, *arg, file=sys.stderr,
                          ^
SyntaxError: invalid syntax

**Comment by mweinelt** [comment]
Well yes, because it uses the newer print function that python3 provides. But even when fixing that by importing print_function from future python2 does not provide the ipaddress module.

Also depending on which distro you use "python" may be a link to either python2 or python3 at this point. Just prefix check like `python3 check` for now.

**Comment by 3dfxatwork** [comment]
I know, my idea with this ticket was to better communicate this. I will close this as clarified.

**Comment by mweinelt** [comment]
No, not really. We are going to deploy a better solution, it's just that we have to think this through first, before making those changes.
